---
title: "FML assignment"
author: "Shivani Pitla"
date: "2022-10-03"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(class)
library(dplyr)
library(caret)
library(tinytex)
universalbank=read.csv("C:/Users/shiva/Downloads/UniversalBank (1).csv")

#deleting unnecessary columns, such as ID and Zip code
universalbank$ID<-NULL
universalbank$ZIP.Code<-NULL
View(universalbank)

#converting to a variable factor
universalbank$Personal.Loan=as.factor(universalbank$Personal.Loan)

#running is.na command to check if there are any NA values
head(is.na(universalbank))

#converting education into character
universalbank$Education=as.character(universalbank$Education)

#Creating dummy  variables
education_1 <- ifelse(universalbank$Education==1 ,1,0)

education_2 <- ifelse(universalbank$Education==2 ,1,0)

education_3 <- ifelse(universalbank$Education==3 ,1,0)

ub_2<-data.frame(Age=universalbank$Age,Experience=universalbank$Experience,Income=universalbank$Income,Family=universalbank$Family,CCAvg=universalbank$CCAvg, education_1=education_1,education_2=education_2,education_3=education_3,Personal.Loan=universalbank$Personal.Loan,Mortgage=universalbank$Mortgage,Securities.Account=universalbank$Securities.Account,CD.Account=universalbank$CD.Account,Online=universalbank$Online,CreditCard=universalbank$CreditCard)

#setting up testdata
UBtest_1<-data.frame(Age=40,Experience=10,Income=84,Family=2,CCAvg=2,education_1=0,education_2=1,education_3=0,Mortgage=0,Securities.Account=0,CD.Account=0,Online=1,CreditCard=1)

#separating training and test sets of data
set.seed(130)
ub_dummy<- createDataPartition(ub_2$Personal.Loan,p=.6,list=FALSE,times=1)
train1_ub <- ub_2[ub_dummy, ]
valid1_ub<- ub_2[-ub_dummy, ]

#Normalization
ub_norm=preProcess(train1_ub[,-(6:9)],method=c("center","scale"))
trainNorm_ub =predict(ub_norm,train1_ub)
validNorm_ub =predict(ub_norm,valid1_ub)
testNorm_ub =predict(ub_norm,UBtest_1)

View(trainNorm_ub)

#printing knn algorithm

predicttrain_ub<-trainNorm_ub[,-9]
trainsample_ub<-trainNorm_ub[,9]
predictvalid_ub<-validNorm_ub[,-9]
validsample_ub<-validNorm_ub[,9]

predict_ub<-knn(predicttrain_ub, testNorm_ub, cl=trainsample_ub,k=1)
predict_ub

predict_uvb <- knn(predicttrain_ub, predictvalid_ub, cl=trainsample_ub, k=1)

#The customer has rejected the loan offer. When the k value is 0, it is decided.

#printing ou the best value of k
set.seed(130)
grid_ub<-expand.grid(k=seq(1:30))                  
model_ub<-train(Personal.Loan~.,data=trainNorm_ub,method="knn",tuneGrid=grid_ub)
model_ub

value_k<-model_ub$bestTune[[1]]

#confusion matrix - validation dataset
confusionMatrix(predict_uvb,validsample_ub)


#50:30:20 Repartition
data_part_new <- createDataPartition(ub_2$Personal.Loan,p=0.5, list = F)
Train_new <- ub_2[data_part_new,]
Train_db_new <- ub_2[-data_part_new,]

data_part_new_1 <- createDataPartition(Train_db_new$Personal.Loan, p=0.6, list = F)
validate_new <- Train_db_new[data_part_new_1,]
test_new <- Train_db_new[-data_part_new_1,]

#Normalization
norm_new <- preProcess(Train_new[,-(6:9)], method=c("center","scale"))
Train_new_p <- predict(norm_new, Train_new)
Validate_new_p <- predict(norm_new, validate_new)
Test_new_p <- predict(norm_new, test_new)

#predictors and labels
train_pre <- Train_new_p[,-9]
validate_pre <- Validate_new_p[,-9]
test_pre <- Test_new_p[,-9]

train_l <- Train_new_p[,9]
validate_l <- Validate_new_p[,9]
test_l <- Test_new_p[,9]

#knn
knn_t <- knn(train_pre,train_pre,cl= train_l, k=value_k)

knn_v <- knn(train_pre,validate_pre,cl=train_l, k=value_k)

knn_tes <- knn(train_pre,test_pre,cl=train_l, k=value_k)

confusionMatrix(knn_t,train_l)
confusionMatrix(knn_v,validate_l)
confusionMatrix(knn_tes,test_l) 
```
